apiVersion: v1
kind: Service
metadata:
  name: fortress-service
spec:
  type: NodePort
  selector:
    app: fortress
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
